// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH38k7nTJzAB8RiqZs3q_Z5ZsrKzquFZ4',
    appId: '1:552861229382:web:7d8ab874a4c62ff65fc547',
    messagingSenderId: '552861229382',
    projectId: 'firsttest-a81fa',
    authDomain: 'firsttest-a81fa.firebaseapp.com',
    storageBucket: 'firsttest-a81fa.appspot.com',
    measurementId: 'G-CDT0G7SPY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8EHZvIE2A1Y1LaC9gj6-oFikdOLfSMnI',
    appId: '1:552861229382:android:8636f0f9a209cd765fc547',
    messagingSenderId: '552861229382',
    projectId: 'firsttest-a81fa',
    storageBucket: 'firsttest-a81fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5D7AfP23NKdiy8neqPudTNT4bl3SFICE',
    appId: '1:552861229382:ios:5b5ae223e0d0a4a65fc547',
    messagingSenderId: '552861229382',
    projectId: 'firsttest-a81fa',
    storageBucket: 'firsttest-a81fa.appspot.com',
    iosBundleId: 'com.example.locationTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5D7AfP23NKdiy8neqPudTNT4bl3SFICE',
    appId: '1:552861229382:ios:5b5ae223e0d0a4a65fc547',
    messagingSenderId: '552861229382',
    projectId: 'firsttest-a81fa',
    storageBucket: 'firsttest-a81fa.appspot.com',
    iosBundleId: 'com.example.locationTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH38k7nTJzAB8RiqZs3q_Z5ZsrKzquFZ4',
    appId: '1:552861229382:web:eb55ac20fc5df6a15fc547',
    messagingSenderId: '552861229382',
    projectId: 'firsttest-a81fa',
    authDomain: 'firsttest-a81fa.firebaseapp.com',
    storageBucket: 'firsttest-a81fa.appspot.com',
    measurementId: 'G-TYES38QYW0',
  );
}
